//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceptionHandling.CodeContracts.ConsoleUi {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MenuResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MenuResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExceptionHandling.CodeContracts.ConsoleUi.MenuResources", typeof(MenuResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assemblies (.dll)|*.dll.
        /// </summary>
        internal static string AssembliesFilter {
            get {
                return ResourceManager.GetString("AssembliesFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodeAuthorInfo assembly extraction by opening assembly.
        /// </summary>
        internal static string AssemblyExtractionMenuOptionName {
            get {
                return ResourceManager.GetString("AssemblyExtractionMenuOptionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodeAuthorInfo assembly extraction by specified path.
        /// </summary>
        internal static string AssemblyPathExtractionMenuOptionName {
            get {
                return ResourceManager.GetString("AssemblyPathExtractionMenuOptionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception: {0}.
        /// </summary>
        internal static string ExceptionFormat {
            get {
                return ResourceManager.GetString("ExceptionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message: {0}.
        /// </summary>
        internal static string ExceptionMessageFormat {
            get {
                return ResourceManager.GetString("ExceptionMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception SourceType {0} was thrown..
        /// </summary>
        internal static string ExceptionTypeThrownMessageFormat {
            get {
                return ResourceManager.GetString("ExceptionTypeThrownMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key to continue or {0} to quit... .
        /// </summary>
        internal static string MenuApplicationContinueMessageFormat {
            get {
                return ResourceManager.GetString("MenuApplicationContinueMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a menu option or press {0} to quit... .
        /// </summary>
        internal static string MenuApplicationFooterFormat {
            get {
                return ResourceManager.GetString("MenuApplicationFooterFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] {1}.
        /// </summary>
        internal static string MenuOptionFormat {
            get {
                return ResourceManager.GetString("MenuOptionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press path to an assembly....
        /// </summary>
        internal static string PressPathToAssemblyMessage {
            get {
                return ResourceManager.GetString("PressPathToAssemblyMessage", resourceCulture);
            }
        }
    }
}
